#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

xmodmap ~/.Xmodmap
xbindkeys

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

compton -CGb
# /usr/lib/notify-osd/notify-osd
# exec mate-session

exec i3
